name = "CarbonI"
uuid = "48794586-7e9f-4ac7-a6dd-1daf0cf5e926"
authors = ["Christian Frankenberg <fronge@gmail.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
InstrumentOperator = "9e589c1b-9e01-4e00-831a-aa39ce86e3ef"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
PlotlyKaleido = "f2990250-8cf9-495f-b13a-cce12b45703c"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
vSmartMOM = "7ba11eeb-0a61-4a04-a413-bf612cc2007e"

[compat]
Artifacts = "1.11.0"
CairoMakie = "0.10.12"
ColorSchemes = "3.29.0"
Colors = "0.12.11"
Conda = "1.10.2"
DSP = "0.7.10"
DataFrames = "1.7.0"
DocStringExtensions = "0.9.3"
FiniteDiff = "2.27.0"
GeoMakie = "0.5.1"
InstrumentOperator = "0.1.2"
Kronecker = "0.5.5"
MAT = "0.10.7"
Makie = "0.19.12"
Pkg = "1.11.0"
PlotlyBase = "0.8.19"
PlotlyKaleido = "2.2.5"
PrettyTables = "2.4.0"
Revise = "3.6.5"
StaticArrays = "1.9.13"
TimeSeries = "0.24.2"
UnitfulEquivalences = "0.2.0"
vSmartMOM = "1.1.0"
