[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CarbonI = "48794586-7e9f-4ac7-a6dd-1daf0cf5e926"
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoArrays = "2fb1d81b-e6a0-5fc5-82e6-8e06903437ab"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Insolation = "e98cc03f-d57e-4e3c-b70c-8d51efe9e0d8"
InstrumentOperator = "9e589c1b-9e01-4e00-831a-aa39ce86e3ef"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
vSmartMOM = "7ba11eeb-0a61-4a04-a413-bf612cc2007e"
